version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: hotelrooms
    tty: true
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hotelrooms
      - MYSQL_USER=xplora
      - MYSQL_PASSWORD=xplora

volumes:
  mysql:
    driver: local