scalar DateTime

type User {
    id: Int!
    email: String!
    firstName: String!
    lastName: String!
    createdAt: DateTime!
    bookings: [Booking]
}

type Hotel {
    id: Int!
    name: String!
    location: String!
    rooms: [Room]
}

type Room {
    id: Int!
    hotel: Hotel,
    hotelID: Int!
    title: String!
    image: String!
    singleBed: Int!
    doubleBed: Int!
    wifi: Int!
    tv: Int!
    bookings: [Booking]
}

type Booking {
    user: User!
    userId: Int!
    startDate: DateTime!
    endDate: DateTime!
    room: Room! 
}

type Query {
    users: [User]
    hotels: [Hotel]
    getHotelById(id: Int!, startDate: DateTime, endDate: DateTime): Hotel!
    getUserByEmail(email: String!): User!
}

type createBooking {
    userId: Int!
    hotelId: Int!
    roomId: Int!
    startDate: DateTime!
    endDate: DateTime!
}

type Mutation {
    createUser (
        email: String!
        firstName: String!
        lastName: String!
    ): User!

    createBooking (
        userId: Int!
        hotelId: Int!
        roomId: Int!
        startDate: DateTime!
        endDate: DateTime!
    ): createBooking!
}